name:                bit-protocol
version:             0.2.2.0
synopsis:            Encode binary protocols with some odd bit numbers into a bytestring
description:         Encode binary protocols with some odd bit numbers into a bytestring.
homepage:            https://github.com/k-bx/bit-protocol#readme
license:             BSD3
author:              Kostiantyn Rybnikov
maintainer:          k-bx@k-bx.com
copyright:           Kostiantyn Rybnikov
category:            Data, Parsing, Bits, Bytes, Protocols
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - base64-bytestring
  - bytestring
  - dlist
  - ghc-prim
  - QuickCheck

library:
  source-dirs:      src

ghc-options:
  -Wall

tests:
  test:
    main: tests.hs
    source-dirs: test
    dependencies:
      - bit-protocol
      - tasty
      - tasty-hunit
      - tasty-quickcheck
